/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { SimpleFactory, SimpleFactoryInterface } from "../SimpleFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_governance",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "market",
        type: "address",
      },
    ],
    name: "CreateMarket",
    type: "event",
  },
  {
    inputs: [],
    name: "createMarket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getMarketInfo",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "market",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "createTime",
            type: "uint64",
          },
        ],
        internalType: "struct ISimpleFactory.MarketInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "marketId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class SimpleFactory__factory {
  static readonly abi = _abi;
  static createInterface(): SimpleFactoryInterface {
    return new Interface(_abi) as SimpleFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SimpleFactory {
    return new Contract(address, _abi, runner) as unknown as SimpleFactory;
  }
}
