/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleCore } from "./SimpleCore";
export * as factories from "./factories";
export { SimpleCore__factory } from "./factories/SimpleCore__factory";
