/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleFactory } from "./SimpleFactory";
export * as factories from "./factories";
export { SimpleFactory__factory } from "./factories/SimpleFactory__factory";
